aikido changes
personalrobotics/pr-ordata pull request #24
Opened 2017-04-29 22:18 UTC by pengjujin

new urdf and tag json files to make pr_ordata compatible with aikido

2017-04-29 23:14 UTC, gilwoolee commented
What are the updates here? Could you resolve the conflicts? Some of those URDFs in the master branch might have been recently added by @yskim041.

2017-05-01 16:06 UTC, pengjujin reviewed
remove some of the random string in the urdf please

2017-05-01 16:06 UTC, pengjujin commented on data/objects/plastic_bowl.kinbody.xml
> +I've mos
Remove this line

2017-05-01 16:06 UTC, pengjujin commented on data/objects/table_mike.urdf
> +Status API Training Shop Blog About
Remove this line

2017-05-01 16:06 UTC, pengjujin commented on data/objects/aikido_tag_data_bowl_glass.json
> +}
remove new line

2017-05-16 20:56 UTC, brianhou requested changes
Not all the tags from `tag_data.json` are in `aikido_tag_data.json`, so it's not yet a drop-in replacement. It seems like it might just be a simple re-formatting from one to the other; if that's the case, we should do that before merging this PR.

Nit: can we rename `aikido_tag_data.json` to something more meaningful? Perhaps `urdf_tag_data.json`, if that's the main difference.

2018-04-21 22:42 UTC, jslee02 commented
Does anyone want to take over this PR? :smiley:

2018-04-21 23:00 UTC, yskim041 commented
I already added new tag data files that follow the theme of this PR in #32. I will look into this and clean up, or we can just drop this PR since we are not using the new objects in this PR.

2022-08-16 18:22 UTC, closed without merging